### ISSUE TITLE
Do not use PDU name, use control packets to match spec

### ISSUE THREAD

**Issue by mremond** [FluuxIO/mqtt#4]
Rename pdu.go to control_packets.go and use CP prefix instead of PDU (Protocol Data Unit) to better match MQTT spec.

**Comment by mremond** [comment]
Ah sorry, I had not seen you patch. I used a suffix packet instead of CP prefix.
@prefiks Which version do you prefer ?

**Comment by prefiks** [comment]
No special preference, you probably seen more go code, so may know which one is used more?

**Comment by prefiks** [comment]
After seeing your patch, *Packet seems clearer

**Comment by mremond** [comment]
ok, thanks, merged.
